from __future__ import annotations

from enum import StrEnum


class ApiErrorCode(StrEnum):
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INACTIVE_USER = "INACTIVE_USER"
    INVALID_TOKEN = "INVALID_TOKEN"
    INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    INVALID_ROLE = "INVALID_ROLE"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    RESOURCE_CONFLICT = "RESOURCE_CONFLICT"
    NO_ACTIVE_REVISION = "NO_ACTIVE_REVISION"
    AMBIGUOUS_CURRENT_REVISION = "AMBIGUOUS_CURRENT_REVISION"
    INVALID_REQUEST = "INVALID_REQUEST"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    IDEMPOTENCY_IN_PROGRESS = "IDEMPOTENCY_IN_PROGRESS"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    GOVERNED_TRANSACTION_FAILED = "GOVERNED_TRANSACTION_FAILED"


class ResourceType(StrEnum):
    MATERIAL = "MATERIAL"
    COATING = "COATING"
    STACK_UP = "STACK_UP"
    ELECTRODE = "ELECTRODE"
    WELD_GUN = "WELD_GUN"
    WELD_SCHEDULE = "WELD_SCHEDULE"
    MATERIAL_REVISION = "MATERIAL_REVISION"
    WELD_SCHEDULE_REVISION = "WELD_SCHEDULE_REVISION"
    WELD_POINT = "WELD_POINT"
    USER = "USER"
    PROJECT = "PROJECT"
