"""engineering library foundation

Revision ID: 0011_engineering_library_foundation
Revises: 0010_digital_weld_passport
"""
import sqlalchemy as sa

from alembic import op

revision = '0011_engineering_library_foundation'
down_revision = '0010_digital_weld_passport'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineering_coatings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coating_id', sa.String(length=120), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_actor_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coating_id', name='uq_engineering_coatings_coating_id')
    )
    op.create_table('engineering_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.String(length=120), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_actor_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', name='uq_engineering_materials_material_id')
    )
    op.create_table('engineering_stack_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stack_id', sa.String(length=120), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_actor_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stack_id', name='uq_engineering_stack_ups_stack_id')
    )
    op.create_table('engineering_coating_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engineering_coating_id', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('supersedes_revision_id', sa.Integer(), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('DRAFT', 'REVIEW', 'VALIDATED', 'APPROVED', 'ACTIVE', 'SUPERSEDED', 'RETIRED', 'ARCHIVED', name='ck_engineering_coating_revisions_lifecycle_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_class', sa.Enum('SOURCE_BACKED', 'EXPERIMENTAL', 'FIELD_CALIBRATED', 'DERIVED', 'PROPOSED', 'UNRESOLVED', name='ck_engineering_coating_revisions_source_class', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('family', sa.String(length=120), nullable=False),
    sa.Column('designation', sa.String(length=160), nullable=False),
    sa.Column('nominal_thickness_um', sa.Float(), nullable=True),
    sa.Column('electrical_contact_effect', sa.String(length=160), nullable=True),
    sa.Column('electrode_wear_effect', sa.String(length=160), nullable=True),
    sa.Column('evidence_reference_ids', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('canonicalization_version', sa.String(length=40), nullable=False),
    sa.Column('hash_algorithm', sa.String(length=40), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('software_version', sa.String(length=80), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_actor_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('nominal_thickness_um IS NULL OR nominal_thickness_um > 0', name='ck_engineering_coating_revisions_positive_thickness'),
    sa.CheckConstraint('revision_number > 0', name='ck_engineering_coating_revisions_positive_revision'),
    sa.CheckConstraint('supersedes_revision_id IS NULL OR supersedes_revision_id != id', name='ck_engineering_coating_revisions_not_self_superseding'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['engineering_coating_id', 'supersedes_revision_id'], ['engineering_coating_revisions.engineering_coating_id', 'engineering_coating_revisions.id'], name='fk_engineering_coating_revisions_same_coating_supersession', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['engineering_coating_id'], ['engineering_coatings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engineering_coating_id', 'id', name='uq_engineering_coating_revisions_context_internal_id'),
    sa.UniqueConstraint('engineering_coating_id', 'revision_number', name='uq_engineering_coating_revisions_logical_revision'),
    sa.UniqueConstraint('supersedes_revision_id', name='uq_engineering_coating_revisions_single_successor')
    )
    op.create_index(op.f('ix_engineering_coating_revisions_engineering_coating_id'), 'engineering_coating_revisions', ['engineering_coating_id'], unique=False)
    op.create_table('engineering_material_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engineering_material_id', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('supersedes_revision_id', sa.Integer(), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('DRAFT', 'REVIEW', 'VALIDATED', 'APPROVED', 'ACTIVE', 'SUPERSEDED', 'RETIRED', 'ARCHIVED', name='ck_engineering_material_revisions_lifecycle_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_class', sa.Enum('SOURCE_BACKED', 'EXPERIMENTAL', 'FIELD_CALIBRATED', 'DERIVED', 'PROPOSED', 'UNRESOLVED', name='ck_engineering_material_revisions_source_class', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('family', sa.String(length=120), nullable=False),
    sa.Column('grade', sa.String(length=160), nullable=False),
    sa.Column('form', sa.String(length=120), nullable=True),
    sa.Column('thickness_min_mm', sa.Float(), nullable=True),
    sa.Column('thickness_max_mm', sa.Float(), nullable=True),
    sa.Column('weldability_class', sa.String(length=120), nullable=True),
    sa.Column('contact_resistance_class', sa.String(length=120), nullable=True),
    sa.Column('properties_snapshot', sa.JSON(), nullable=False),
    sa.Column('evidence_reference_ids', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('canonicalization_version', sa.String(length=40), nullable=False),
    sa.Column('hash_algorithm', sa.String(length=40), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('software_version', sa.String(length=80), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_actor_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('revision_number > 0', name='ck_engineering_material_revisions_positive_revision'),
    sa.CheckConstraint('supersedes_revision_id IS NULL OR supersedes_revision_id != id', name='ck_engineering_material_revisions_not_self_superseding'),
    sa.CheckConstraint('thickness_max_mm IS NULL OR thickness_max_mm > 0', name='ck_engineering_material_revisions_positive_max_thickness'),
    sa.CheckConstraint('thickness_min_mm IS NULL OR thickness_max_mm IS NULL OR thickness_max_mm >= thickness_min_mm', name='ck_engineering_material_revisions_thickness_window'),
    sa.CheckConstraint('thickness_min_mm IS NULL OR thickness_min_mm > 0', name='ck_engineering_material_revisions_positive_min_thickness'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['engineering_material_id', 'supersedes_revision_id'], ['engineering_material_revisions.engineering_material_id', 'engineering_material_revisions.id'], name='fk_engineering_material_revisions_same_material_supersession', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['engineering_material_id'], ['engineering_materials.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engineering_material_id', 'id', name='uq_engineering_material_revisions_context_internal_id'),
    sa.UniqueConstraint('engineering_material_id', 'revision_number', name='uq_engineering_material_revisions_logical_revision'),
    sa.UniqueConstraint('supersedes_revision_id', name='uq_engineering_material_revisions_single_successor')
    )
    op.create_index(op.f('ix_engineering_material_revisions_engineering_material_id'), 'engineering_material_revisions', ['engineering_material_id'], unique=False)
    op.create_table('engineering_stack_up_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engineering_stack_up_id', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('supersedes_revision_id', sa.Integer(), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('DRAFT', 'REVIEW', 'VALIDATED', 'APPROVED', 'ACTIVE', 'SUPERSEDED', 'RETIRED', 'ARCHIVED', name='ck_engineering_stack_up_revisions_lifecycle_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_class', sa.Enum('SOURCE_BACKED', 'EXPERIMENTAL', 'FIELD_CALIBRATED', 'DERIVED', 'PROPOSED', 'UNRESOLVED', name='ck_engineering_stack_up_revisions_source_class', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('adhesive_present', sa.Boolean(), nullable=False),
    sa.Column('interface_notes', sa.Text(), nullable=True),
    sa.Column('evidence_reference_ids', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('canonicalization_version', sa.String(length=40), nullable=False),
    sa.Column('hash_algorithm', sa.String(length=40), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('software_version', sa.String(length=80), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_actor_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('revision_number > 0', name='ck_engineering_stack_up_revisions_positive_revision'),
    sa.CheckConstraint('supersedes_revision_id IS NULL OR supersedes_revision_id != id', name='ck_engineering_stack_up_revisions_not_self_superseding'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['engineering_stack_up_id', 'supersedes_revision_id'], ['engineering_stack_up_revisions.engineering_stack_up_id', 'engineering_stack_up_revisions.id'], name='fk_engineering_stack_up_revisions_same_stack_supersession', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['engineering_stack_up_id'], ['engineering_stack_ups.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engineering_stack_up_id', 'id', name='uq_engineering_stack_up_revisions_context_internal_id'),
    sa.UniqueConstraint('engineering_stack_up_id', 'revision_number', name='uq_engineering_stack_up_revisions_logical_revision'),
    sa.UniqueConstraint('supersedes_revision_id', name='uq_engineering_stack_up_revisions_single_successor')
    )
    op.create_index(op.f('ix_engineering_stack_up_revisions_engineering_stack_up_id'), 'engineering_stack_up_revisions', ['engineering_stack_up_id'], unique=False)
    op.create_table('engineering_stack_layers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stack_up_revision_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('material_revision_id', sa.Integer(), nullable=False),
    sa.Column('coating_revision_id', sa.Integer(), nullable=True),
    sa.Column('thickness_mm', sa.Float(), nullable=False),
    sa.Column('orientation', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('sequence > 0', name='ck_engineering_stack_layers_positive_sequence'),
    sa.CheckConstraint('thickness_mm > 0', name='ck_engineering_stack_layers_positive_thickness'),
    sa.ForeignKeyConstraint(['coating_revision_id'], ['engineering_coating_revisions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_revision_id'], ['engineering_material_revisions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stack_up_revision_id'], ['engineering_stack_up_revisions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stack_up_revision_id', 'sequence', name='uq_engineering_stack_layers_revision_sequence')
    )
    op.create_index(op.f('ix_engineering_stack_layers_coating_revision_id'), 'engineering_stack_layers', ['coating_revision_id'], unique=False)
    op.create_index(op.f('ix_engineering_stack_layers_material_revision_id'), 'engineering_stack_layers', ['material_revision_id'], unique=False)
    op.create_index(op.f('ix_engineering_stack_layers_stack_up_revision_id'), 'engineering_stack_layers', ['stack_up_revision_id'], unique=False)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engineering_stack_layers_stack_up_revision_id'), table_name='engineering_stack_layers')
    op.drop_index(op.f('ix_engineering_stack_layers_material_revision_id'), table_name='engineering_stack_layers')
    op.drop_index(op.f('ix_engineering_stack_layers_coating_revision_id'), table_name='engineering_stack_layers')
    op.drop_table('engineering_stack_layers')
    op.drop_index(op.f('ix_engineering_stack_up_revisions_engineering_stack_up_id'), table_name='engineering_stack_up_revisions')
    op.drop_table('engineering_stack_up_revisions')
    op.drop_index(op.f('ix_engineering_material_revisions_engineering_material_id'), table_name='engineering_material_revisions')
    op.drop_table('engineering_material_revisions')
    op.drop_index(op.f('ix_engineering_coating_revisions_engineering_coating_id'), table_name='engineering_coating_revisions')
    op.drop_table('engineering_coating_revisions')
    op.drop_table('engineering_stack_ups')
    op.drop_table('engineering_materials')
    op.drop_table('engineering_coatings')
    # ### end Alembic commands ###
