"""electrode, weld gun and weld schedule persistence

Revision ID: 0012_electrode_weldgun_weldschedule_persistence
Revises: 0011_engineering_library_foundation
"""
import sqlalchemy as sa

from alembic import op

revision = '0012_electrode_weldgun_weldschedule_persistence'
down_revision = '0011_engineering_library_foundation'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineering_electrodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('electrode_id', sa.String(length=120), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_actor_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('electrode_id', name='uq_engineering_electrodes_electrode_id')
    )
    op.create_table('engineering_weld_guns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gun_id', sa.String(length=120), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_actor_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gun_id', name='uq_engineering_weld_guns_gun_id')
    )
    op.create_table('engineering_weld_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.String(length=120), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_actor_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', name='uq_engineering_weld_schedules_schedule_id')
    )
    op.create_table('engineering_electrode_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engineering_electrode_id', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('supersedes_revision_id', sa.Integer(), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('DRAFT', 'REVIEW', 'VALIDATED', 'APPROVED', 'ACTIVE', 'SUPERSEDED', 'RETIRED', 'ARCHIVED', name='ck_engineering_electrode_revisions_lifecycle_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_class', sa.Enum('SOURCE_BACKED', 'EXPERIMENTAL', 'FIELD_CALIBRATED', 'DERIVED', 'PROPOSED', 'UNRESOLVED', name='ck_engineering_electrode_revisions_source_class', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('face_geometry', sa.Enum('FLAT', 'DOME', 'RADIUS', 'TRUNCATED_CONE', 'CUSTOM', name='ck_engineering_electrode_revisions_face_geometry', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('face_diameter_mm', sa.Float(), nullable=False),
    sa.Column('tip_diameter_mm', sa.Float(), nullable=True),
    sa.Column('radius_mm', sa.Float(), nullable=True),
    sa.Column('included_angle_deg', sa.Float(), nullable=True),
    sa.Column('material_designation', sa.String(length=120), nullable=False),
    sa.Column('cooling_channel_diameter_mm', sa.Float(), nullable=True),
    sa.Column('recommended_flow_lpm', sa.Float(), nullable=True),
    sa.Column('recommended_max_inlet_temp_c', sa.Float(), nullable=True),
    sa.Column('evidence_reference_ids', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('canonicalization_version', sa.String(length=40), nullable=False),
    sa.Column('hash_algorithm', sa.String(length=40), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('software_version', sa.String(length=80), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_actor_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('face_diameter_mm > 0', name='ck_engineering_electrode_revisions_positive_face_diameter'),
    sa.CheckConstraint('revision_number > 0', name='ck_engineering_electrode_revisions_positive_revision'),
    sa.CheckConstraint('supersedes_revision_id IS NULL OR supersedes_revision_id != id', name='ck_engineering_electrode_revisions_not_self_superseding'),
    sa.CheckConstraint('tip_diameter_mm IS NULL OR tip_diameter_mm > 0', name='ck_engineering_electrode_revisions_positive_tip_diameter'),
    sa.CheckConstraint('radius_mm IS NULL OR radius_mm > 0', name='ck_engineering_electrode_revisions_positive_radius'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['engineering_electrode_id', 'supersedes_revision_id'], ['engineering_electrode_revisions.engineering_electrode_id', 'engineering_electrode_revisions.id'], name='fk_engineering_electrode_revisions_same_electrode_supersession', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['engineering_electrode_id'], ['engineering_electrodes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engineering_electrode_id', 'id', name='uq_engineering_electrode_revisions_context_internal_id'),
    sa.UniqueConstraint('engineering_electrode_id', 'revision_number', name='uq_engineering_electrode_revisions_logical_revision'),
    sa.UniqueConstraint('supersedes_revision_id', name='uq_engineering_electrode_revisions_single_successor')
    )
    op.create_index(op.f('ix_engineering_electrode_revisions_engineering_electrode_id'), 'engineering_electrode_revisions', ['engineering_electrode_id'], unique=False)
    op.create_table('engineering_weld_gun_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engineering_weld_gun_id', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('supersedes_revision_id', sa.Integer(), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('DRAFT', 'REVIEW', 'VALIDATED', 'APPROVED', 'ACTIVE', 'SUPERSEDED', 'RETIRED', 'ARCHIVED', name='ck_engineering_weld_gun_revisions_lifecycle_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_class', sa.Enum('SOURCE_BACKED', 'EXPERIMENTAL', 'FIELD_CALIBRATED', 'DERIVED', 'PROPOSED', 'UNRESOLVED', name='ck_engineering_weld_gun_revisions_source_class', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('actuation_type', sa.Enum('SERVO', 'PNEUMATIC', 'HYDRAULIC', 'MANUAL', 'OTHER', name='ck_engineering_weld_gun_revisions_actuation_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('max_force_kn', sa.Float(), nullable=False),
    sa.Column('throat_depth_mm', sa.Float(), nullable=True),
    sa.Column('max_opening_mm', sa.Float(), nullable=True),
    sa.Column('transformer_snapshot', sa.JSON(), nullable=True),
    sa.Column('controller_snapshot', sa.JSON(), nullable=True),
    sa.Column('cooling_snapshot', sa.JSON(), nullable=True),
    sa.Column('evidence_reference_ids', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('canonicalization_version', sa.String(length=40), nullable=False),
    sa.Column('hash_algorithm', sa.String(length=40), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('software_version', sa.String(length=80), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_actor_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_force_kn > 0', name='ck_engineering_weld_gun_revisions_positive_max_force'),
    sa.CheckConstraint('max_opening_mm IS NULL OR max_opening_mm > 0', name='ck_engineering_weld_gun_revisions_positive_max_opening'),
    sa.CheckConstraint('revision_number > 0', name='ck_engineering_weld_gun_revisions_positive_revision'),
    sa.CheckConstraint('supersedes_revision_id IS NULL OR supersedes_revision_id != id', name='ck_engineering_weld_gun_revisions_not_self_superseding'),
    sa.CheckConstraint('throat_depth_mm IS NULL OR throat_depth_mm > 0', name='ck_engineering_weld_gun_revisions_positive_throat_depth'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['engineering_weld_gun_id', 'supersedes_revision_id'], ['engineering_weld_gun_revisions.engineering_weld_gun_id', 'engineering_weld_gun_revisions.id'], name='fk_engineering_weld_gun_revisions_same_gun_supersession', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['engineering_weld_gun_id'], ['engineering_weld_guns.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engineering_weld_gun_id', 'id', name='uq_engineering_weld_gun_revisions_context_internal_id'),
    sa.UniqueConstraint('engineering_weld_gun_id', 'revision_number', name='uq_engineering_weld_gun_revisions_logical_revision'),
    sa.UniqueConstraint('supersedes_revision_id', name='uq_engineering_weld_gun_revisions_single_successor')
    )
    op.create_index(op.f('ix_engineering_weld_gun_revisions_engineering_weld_gun_id'), 'engineering_weld_gun_revisions', ['engineering_weld_gun_id'], unique=False)
    op.create_table('engineering_weld_schedule_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engineering_weld_schedule_id', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('supersedes_revision_id', sa.Integer(), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('DRAFT', 'REVIEW', 'VALIDATED', 'APPROVED', 'ACTIVE', 'SUPERSEDED', 'RETIRED', 'ARCHIVED', name='ck_engineering_weld_schedule_revisions_lifecycle_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_class', sa.Enum('SOURCE_BACKED', 'EXPERIMENTAL', 'FIELD_CALIBRATED', 'DERIVED', 'PROPOSED', 'UNRESOLVED', name='ck_engineering_weld_schedule_revisions_source_class', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('squeeze_cycles', sa.Float(), nullable=False),
    sa.Column('hold_cycles', sa.Float(), nullable=False),
    sa.Column('nominal_force_kn', sa.Float(), nullable=True),
    sa.Column('process_metadata', sa.JSON(), nullable=True),
    sa.Column('evidence_reference_ids', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('canonicalization_version', sa.String(length=40), nullable=False),
    sa.Column('hash_algorithm', sa.String(length=40), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('software_version', sa.String(length=80), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_actor_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('hold_cycles >= 0', name='ck_engineering_weld_schedule_revisions_non_negative_hold'),
    sa.CheckConstraint('nominal_force_kn IS NULL OR nominal_force_kn > 0', name='ck_engineering_weld_schedule_revisions_positive_nominal_force'),
    sa.CheckConstraint('revision_number > 0', name='ck_engineering_weld_schedule_revisions_positive_revision'),
    sa.CheckConstraint('squeeze_cycles >= 0', name='ck_engineering_weld_schedule_revisions_non_negative_squeeze'),
    sa.CheckConstraint('supersedes_revision_id IS NULL OR supersedes_revision_id != id', name='ck_engineering_weld_schedule_revisions_not_self_superseding'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['engineering_weld_schedule_id', 'supersedes_revision_id'], ['engineering_weld_schedule_revisions.engineering_weld_schedule_id', 'engineering_weld_schedule_revisions.id'], name='fk_eng_weld_sched_rev_same_sched_supersession', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['engineering_weld_schedule_id'], ['engineering_weld_schedules.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engineering_weld_schedule_id', 'id', name='uq_engineering_weld_schedule_revisions_context_internal_id'),
    sa.UniqueConstraint('engineering_weld_schedule_id', 'revision_number', name='uq_engineering_weld_schedule_revisions_logical_revision'),
    sa.UniqueConstraint('supersedes_revision_id', name='uq_engineering_weld_schedule_revisions_single_successor')
    )
    op.create_index(op.f('ix_engineering_weld_schedule_revisions_engineering_weld_schedule_id'), 'engineering_weld_schedule_revisions', ['engineering_weld_schedule_id'], unique=False)
    op.create_table('engineering_weld_pulses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engineering_weld_schedule_revision_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('pulse_type', sa.Enum('PREHEAT', 'WELD', 'COOL', 'POSTHEAT', 'TEMPER', 'CUSTOM', name='ck_engineering_weld_pulses_pulse_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('current_ka', sa.Float(), nullable=True),
    sa.Column('duration_cycles', sa.Float(), nullable=False),
    sa.Column('force_kn', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('duration_cycles >= 0', name='ck_engineering_weld_pulses_non_negative_duration'),
    sa.CheckConstraint('sequence_number > 0', name='ck_engineering_weld_pulses_positive_sequence_number'),
    sa.ForeignKeyConstraint(['engineering_weld_schedule_revision_id'], ['engineering_weld_schedule_revisions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engineering_weld_schedule_revision_id', 'sequence_number', name='uq_engineering_weld_pulses_revision_sequence')
    )
    op.create_index(op.f('ix_engineering_weld_pulses_engineering_weld_schedule_revision_id'), 'engineering_weld_pulses', ['engineering_weld_schedule_revision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engineering_weld_pulses_engineering_weld_schedule_revision_id'), table_name='engineering_weld_pulses')
    op.drop_table('engineering_weld_pulses')
    op.drop_index(op.f('ix_engineering_weld_schedule_revisions_engineering_weld_schedule_id'), table_name='engineering_weld_schedule_revisions')
    op.drop_table('engineering_weld_schedule_revisions')
    op.drop_index(op.f('ix_engineering_weld_gun_revisions_engineering_weld_gun_id'), table_name='engineering_weld_gun_revisions')
    op.drop_table('engineering_weld_gun_revisions')
    op.drop_index(op.f('ix_engineering_electrode_revisions_engineering_electrode_id'), table_name='engineering_electrode_revisions')
    op.drop_table('engineering_electrode_revisions')
    op.drop_table('engineering_weld_schedules')
    op.drop_table('engineering_weld_guns')
    op.drop_table('engineering_electrodes')
    # ### end Alembic commands ###
